apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
  namespace: flm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      containers:
        - name: app-service
          image: abbasshaik739/python:appimage1
          ports:
            - containerPort: 5000

#write a horizontal pod autoscaler manifest for the above deployment
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-service-hpa
  namespace: flm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
